export default `,Legend for cell colour coding,Description,,,,Action,,,,,,,
,,,,,,,,,,,,,
,,Data input used in model,,,Do not change,Only fill in the below column - all other columns are auto/prefilled                                                                                                                                                                                             .,,,,,,,
,,Data estimated w/ population scaling,,,Do not change,,,,,,,,
,,Placeholder data - various sources,,,Do not change,,,,,,,,
,,Reference value for scaling city,,,Do not change,,,,,,,,
,,High priority data point,,,Focus for research on alternative data points or proxy analysis to check pre-filled data,,,,,,,,
,,Moderate priority data point,,,Only add when more relevant data point / rapid proxy analysis is available,,,,,,,,
,,Low priority data point,,,Only add when more relevant data point is immediately available ,,,,,,,,
,,,,,,,,,,,,,
,Data - City input sheet,Preferred unit,Data used in model,Pre-filled data (do not change this value),Source of pre-filled data,Data to be filled in by city,Priority for city to fill in,Source of data filled in by city,Comment,,,,
,,,,,,,,,,,,,
,,,,,,,,,,,,,
,Demographic data,,,Pre-filled data (do not change this value),,Fill city specific data here,,Add source here,Comment,,,,
,Population,Capita,"  820,000 ","  820,000 ","  801,545 ","  820,000 ",High,,,,,,
,Expected annual population growth (up until 2030),% per year,0.2%,0.2%,,,High,,,,,,
,City Area,km2,  139 ,  139 ,,,High,,,,,,
,,,,,,,,,,,,,
,Passenger transportation,,,,,,,Add source here,Comment,,,,
,Transportation need,,,,,,,,,,,,
,Total transportation need - passenger transport,,,,,,,,,,,,
,Transport need - passenger cars + motorcycles,Million passenger-kilometers / year,"  3,003 ","  3,003 ","  2,935 ",,High,,,,,,
,Transport need - buses,Million passenger-kilometers / year,  482 ,  482 ,  471 ,,High,,,,,,
,Transport need - trains/metro,Million passenger-kilometers / year,  476 ,  476 ,  465 ,,High,,,,,,
,Transport need - walking/cycling,Million passenger-kilometers / year,"  2,063 ","  2,063 ","  2,017 ",,Low,,No impact on model,,,,
,,,,,,,,,,,,,
,Number of passengers per vehicle,,,,,,,,,,,,
,Average passengers per car + motorcycle,passengers / car + motorcycle,  1.2 ,  1.2 ,Valencia estimate - 2019,,High,,,,,,
,Average passengers per bus,passengers / bus,  21 ,  21 ,Valencia estimate - 2019,,High,,,,,,
,Average passengers per metro train,passengers / metro train,  40 ,  40 ,Valencia estimate - 2019,,High,,,,,,
,,,,,,,,,,,,,
,Emission factors,,,,,,,,,,,,
,Passenger car / motorcycle fleet (current average fleet),,,,,,,,,,,,
,CO2e emissions,grams / kilometer,  130 ,  130 ,"Calculated based on Eurostat data, DATASET: Greenhouse gas emissions by source sector (source: EEA) [env_air_gge] & DATASET: Motor vehicle movements on national territory, by vehicles registration [road_tf_vehmov]",,High,,Includes electricity emissions from electric cars,,,,
,NOx emissions,grams / kilometer,  0.61 ,  0.61 ,"Calculated based on Eurostat data, DATASET: Air pollutants by source sector (source: EEA) [env_air_emis] & DATASET: Motor vehicle movements on national territory, by vehicles registration [road_tf_vehmov]",,Low,,,,,,
,PM 2.5 emissions,grams / kilometer,  0.02 ,  0.02 ,"Calculated based on Eurostat data, DATASET: Air pollutants by source sector (source: EEA) [env_air_emis] & DATASET: Motor vehicle movements on national territory, by vehicles registration [road_tf_vehmov]",,Low,,,,,,
,PM 10 emissions,grams / kilometer,  0.03 ,  0.03 ,"Calculated based on Eurostat data, DATASET: Air pollutants by source sector (source: EEA) [env_air_emis] & DATASET: Motor vehicle movements on national territory, by vehicles registration [road_tf_vehmov]",,Low,,,,,,
,,,,,,,,,,,,,
,Buses (average fleet),,,,,,,,,,,,
,CO2e emissions,grams / kilometer,  800 ,  800 ,"Atmospheric emissions Inventory of Madrid City, 2017. Municipal buses + other buses",,High,,Includes electricity emissions from electric busses,,,,
,NOx emissions,grams / kilometer,  3.22 ,  3.22 ,"Atmospheric emissions Inventory of Madrid City, 2017. Municipal buses + other buses",,Low,,,,,,
,PM 2.5 emissions,grams / kilometer,  0.07 ,  0.07 ,"Atmospheric emissions Inventory of Madrid City, 2017. Municipal buses + other buses. Including tyre wear and brake wear. Not including road wear ",,Low,,,,,,
,PM 10 emissions,grams / kilometer,  0.10 ,  0.10 ,"Atmospheric emissions Inventory of Madrid City, 2017. Municipal buses + other buses. Including tyre wear and brake wear. Not including road wear ",,Low,,,,,,
,,,,,,,,,,,,,
,Passenger cars - other data,,,,,,,,,,,,
,Total number of cars + motorcycles in city,Number of cars + motorcycles,"  360,259 ","  360,259 ","  352,151 ",,High,,,,,,
,Share of fleet that is less than 2 years old,% of fleet,10%,10%,"Eurostat, DATASET: Passenger cars, by age [road_eqs_carage]",,Moderate,,,,,,
,Share of fleet fully electric (not including hybrids),% of fleet,0.3%,0.3%,"Eurostat, DATASET: Passenger cars, by type of motor energy [road_eqs_carpda]",,Moderate,,,,,,
,,,,,,,,,,,,,
,Buses - other data,,,,,,,,,,,,
,Number of buses in city bus fleet,Nmbr of buses,  934 ,  934 ,  913 ,,High,,,,,,
,Share of bus fleet as fully electric buses (not including hybrids),% of bus fleet,0.0%,0.0%,"Eurostat, DATASET: Motor coaches, buses and trolley buses, by type of motor energy [road_eqs_busmot]",,Moderate,,,,,,
,Share of bus fleet - biobased,% of bus fleet,0.0%,0.0%,"Eurostat, DATASET: Motor coaches, buses and trolley buses, by type of motor energy [road_eqs_busmot]",,Moderate,,,,,,
,,,,,,,,,,,,,
,Freight transport (road),,,,,,,Add source here,Comment,,,,
,Transportation need,,,,,,,,,,,,
,Total transportation need within city - Road freight transport,,,,,,,,,,,,
,Light duty trucks <3.5 tonnes,Million tonne-kilometers/year,  118 ,  118 ,  115 ,,High,,,,,,
,Heavy duty trucks >3.5 tonnes,Million tonne-kilometers/year,  337 ,  337 ,  329 ,,High,,,,,,
,,,,,,,,,,,,,
,Utilisation/loading,,,,,,,,,,,,
,Average utilisation,,,,,,,,,,,,
,Light duty trucks <3.5 tonnes,% of max load,23%,23%,"Average utilisation urban trucks, based on ACEA (2010) Commercial vehicles and CO2",,Moderate,,,,,,
,Heavy duty trucks >3.5 tonnes,% of max load,45%,45%,"Average utilisation urban trucks, based on ACEA (2010) Commercial vehicles and CO2",,Moderate,,,,,,
,,,,,,,,,,,,,
,Emission factors from transportation,,,,,,,,,,,,
,Light duty trucks <3.5 tonnes,,,,,,,,,,,,
,CO2e emissions,grams / kilometer,  216 ,  216 ,"Atmospheric emissions Inventory of Madrid City, 2017.",,High,,Includes electricity emissions from electric trucks,,,,
,NOx emissions,grams / kilometer,  0.68 ,  0.68 ,"Calculated based on Eurostat data, DATASET: Air pollutants by source sector (source: EEA) [env_air_emis] & DATASET: Motor vehicle movements on national territory, by vehicles registration [road_tf_vehmov]",,Low,,,,,,
,PM 2.5 emissions,grams / kilometer,  0.04 ,  0.04 ,"Calculated based on Eurostat data, DATASET: Air pollutants by source sector (source: EEA) [env_air_emis] & DATASET: Motor vehicle movements on national territory, by vehicles registration [road_tf_vehmov]",,Low,,,,,,
,PM 10 emissions,grams / kilometer,  0.05 ,  0.05 ,"Calculated based on Eurostat data, DATASET: Air pollutants by source sector (source: EEA) [env_air_emis] & DATASET: Motor vehicle movements on national territory, by vehicles registration [road_tf_vehmov]",,Low,,,,,,
,,,,,,,,,,,,,
,Heavy duty trucks >3.5 tonnes,,,,,,,,,,,,
,CO2e emissions,grams / kilometer,  374 ,  374 ,"Atmospheric emissions Inventory of Madrid City, 2017.",,High,,Includes electricity emissions from electric trucks,,,,
,NOx emissions,grams / kilometer,  1.61 ,  1.61 ,"Calculated based on Eurostat data, DATASET: Air pollutants by source sector (source: EEA) [env_air_emis] & DATASET: Motor vehicle movements on national territory, by vehicles registration [road_tf_vehmov]",,Low,,,,,,
,PM 2.5 emissions,grams / kilometer,  0.05 ,  0.05 ,"Calculated based on Eurostat data, DATASET: Air pollutants by source sector (source: EEA) [env_air_emis] & DATASET: Motor vehicle movements on national territory, by vehicles registration [road_tf_vehmov]",,Low,,,,,,
,PM 10 emissions,grams / kilometer,  0.07 ,  0.07 ,"Calculated based on Eurostat data, DATASET: Air pollutants by source sector (source: EEA) [env_air_emis] & DATASET: Motor vehicle movements on national territory, by vehicles registration [road_tf_vehmov]",,Low,,,,,,
,,,,,,,,,,,,,
,Other data,,,,,,,,,,,,
,Number of trucks registered within city,,,,,,,,,,,,
,Light duty trucks <3.5 tonnes,Number of trucks,"  17,641 ","  17,641 ","  17,244 ",,Moderate,,,,,,
,Of which less than 2 years old,%,7%,7%,"Eurostat, DATASET: Lorries and road tractors, by age [road_eqs_lorroa]",,Moderate,,,,,,
,Heavy duty trucks >3.5 tonnes,Number of trucks,"  4,410 ","  4,410 ","  4,311 ",,Moderate,,,,,,
,Of which less than 2 years old,%,4%,4%,"Eurostat, DATASET: Lorries and road tractors, by age [road_eqs_lorroa]",,Moderate,,,,,,
,,,,,,,,,,,,,
,,,,,,,,,,,,,
,Buildings,,,,,,,Add source here,Comment,,,,
,Existing building stock,,,,,,,,,,,,
,Total floor area,,,,,,,,,,,,
,Total floor area (residental & non-residential),Thousand squaremeters,"  78,276 ","  78,276 ","  76,514 ",,High,,,,,,
,,,,,,,,,,,,,
,Energy use in existing buildings,,,,,,,,,,,,
,Average heat use in existing buildings (space heating + domestic hot water),kWh/m2 & year,  140 ,  140 ,Average EU28. Odysee-Mure (2015). Energy Efficiency Trends and Policies in the Household and Tertiary Sectors,,Moderate,,,,,,
,Average electricity use for lighting & appliances,kWh/m2 & year,  41 ,  41 ,Average EU28. Odysee-Mure (2015). Energy Efficiency Trends and Policies in the Household and Tertiary Sectors,,Moderate,,,,,,
,,,,,,,,,,,,,
,Renovation rate (building envelope),,,,,,,,,,,,
,Share of building stock renovated each year,%,1.0%,1.0%,"BPIE (2011) - ""Europe's buildings under the microscope"". http://bpie.eu/wp-content/uploads/2015/10/HR_EU_B_under_microscope_study.pdf",,High,,,,,,
,,,,,,,,,,,,,
,,,,,,,,,,,,,
,,,,,,,,,,,,,
,,,,,,,,,,,,,
,,,,,,,,,,,,,
,,,,,,,,,,,,,
,,,,,,,,,,,,,
,,,,,,,,,,,,,
,,,,,,,,,,,,,
,,,,,,,,,,,,,
,New buildings,,,,,,,,,,,,
,Building standards for new buildings,,,,,,,,,,,,
,Minimum building standard (heat use),kWh / m2 & year,  38 ,  38 ,Madrid standard since 2019,,Moderate,,,,,,
,Top performing building standard (heat use),kWh / m2 & year,  10 ,  10 ,,,Low,,No impact on model,,,,
,,,,,,,,,,,,,
,Share of new buildings built with minimum standard (today),% of new buildings,100%,100%,,,Moderate,,,,,,
,"Share of new buildings built with ""better than minimum"" standard (today)",% of new buildings,0%,0%,,,Moderate,,,,,,
,,,100%,100%,,0%,,,Should sum to 100%,,,,
,,,,,,,,,,,,,
,,,,,,,,,,,,,
,,,,,,,,,,,,,
,,,,,,,,,,,,,
,Heating (of buildings),,,,,,,Add source here,Comment,,,,
,Heat demand & production,,,,,,,,,,,,
,Total heating demand (space heating + domestic hot water + heat for cooking),GWh / y,"  1,630 ","  1,630 ","  1,593 ",,High,,,,,,
,,,,,,,,,,,,,
,Heating technologies,,,,,,,,,,,,
,Share of heating as district heating,%,1%,1%,Valencia - 2019,,High,,,,,,
,Share of heating as local heating,%,99%,99%,Valencia - 2019,,High,,,,,,
,Total,%,100%,100%,,0%,,,Should sum to 100%,,,,
,,,,,,,,,,,,,
,Share of district heating as,,,,,,,,,,,,
,"Fossil (oil, coal, gas) + inefficient electric heating (not heat pumps)",%,60%,60%,Valencia - 2019,,High,,,,,,
,Electric heat pumps / geothermal,%,20%,20%,Valencia - 2019,,High,,,,,,
,"Bio (biogas, biomass)",%,20%,20%,Valencia - 2019,,High,,,,,,
,Waste (fossil & non-fossil waste),%,0%,0%,Valencia - 2019,,High,,,,,,
,Total,%,100%,100%,,0%,,,Should sum to 100%,,,,
,,,,,,,,,,,,,
,Share of waste used in district heating that is fossil / non-fossil,,,,,,,,,,,,
,Fossil share,%,30%,30%,Valencia - 2019,,High,,,,,,
,Non-fossil share,%,70%,70%,Valencia - 2019,,High,,,,,,
,,,100%,100%,,0%,,,Should sum to 100%,,,,
,Share of local heating as,,,,,,,,,,,,
,"Fossil (oil, gas, coal) + inefficient electric heating (not heat pumps)",%,70%,70%,Valencia - 2019,,High,,,,,,
,Electric (heat pumps),%,30%,30%,Valencia - 2019,,High,,,,,,
,Biobased / solar water heating,%,0%,0%,Valencia - 2019,,High,,,,,,
,Total,%,100%,100%,,0%,,,Should sum to 100%,,,,
,,,,,,,,,,,,,
,Emission factors from heat production,,,,,,,,,,,,
,District heating,,,,,,,,,,,,
,CO2e emissions,g / kWh,  200 ,  200 ,Weighted average based on Valencia 2019 District Heating fuel mix (rows 130-133),,High,,Weighted average based on fuel mix for District Heating (rows 130-133),,,,
,NOx emissions,g / kWh,  0.139 ,  0.139 ,Assumption based on data for Italy ,,Low,,,,,,
,PM 2.5 emissions,g / kWh,  0.003 ,  0.003 ,Assumption based on data for Italy ,,Low,,,,,,
,PM 10 emissions,g / kWh,  0.005 ,  0.005 ,Assumption based on data for Italy ,,Low,,,,,,
,,,,,,,,,,,,,
,Local heating,,,,,,,,,,,,
,CO2e emissions,g / kWh,  213 ,  213 ,Weighted average based on Valencia 2019 Local Heating fuel mix (rows 141-143),,High,,Weighted average based on fuel mix for Local Heating (rows 141-143),,,,
,NOx emissions,g / kWh,  0.24 ,  0.24 ,"Atmospheric emissions Inventory of Madrid City, 2017. SNAP 02: residential, commercial and institutional buildings",,Low,,,,,,
,PM 2.5 emissions,g / kWh,  0.02 ,  0.02 ,"Atmospheric emissions Inventory of Madrid City, 2017. SNAP 02: residential, commercial and institutional buildings",,Low,,,,,,
,PM 10 emissions,g / kWh,  0.03 ,  0.03 ,"Atmospheric emissions Inventory of Madrid City, 2017. SNAP 02: residential, commercial and institutional buildings",,Low,,,,,,
,,,,,,,,,,,,,
,Electricity,,,,,,,Add source here,Comment,,,,
,Demand of electricity,,,,,,,,,,,,
,Total demand,,,,,,,,,,,,
,Total electricity demand within city boundaries,GWh / y,"  2,152 ","  2,152 ","  2,104 ",,High,,,,,,
,,,,,,,,,,,,,
,Share of total electricity demand produced by fossil/renewables,,,,,,,,,,,,
,Renewable sources,%,37%,37%,Spanish national electricty consumption - Embers European Electricity Review (2019),,High,,,,,,
,Fossil sources,%,41%,41%,Spanish national electricty consumption - Embers European Electricity Review (2019),,High,,,,,,
,Other (e.g. nuclear),%,22%,22%,Spanish national electricty consumption - Embers European Electricity Review (2019),,Low,,,,,,
,Total,Share,100%,100%,,0%,,,Should sum to 100%,,,,
,,,,,,,,,,,,,
,Emission factors from electricity generation,,,,,,,,,,,,
,CO2e emissions,g / kWh,  222 ,  222 ,Weighted average based on Spanish national grid mix (lines 165-167),,High,,Weighted average based on fuel mix for electricity production (rows 165-167),,,,
,NOx emissions,g / kWh,  0.14 ,  0.14 ,"Calculated based on Eurostat data, DATASET: Air pollutants by source sector (source: EEA) [env_air_emis] & DATASET: Supply, transformation and consumption of electricity [nrg_cb_e]",,Low,,,,,,
,PM 2.5 emissions,g / kWh,  0.00 ,  0.00 ,"Calculated based on Eurostat data, DATASET: Air pollutants by source sector (source: EEA) [env_air_emis] & DATASET: Supply, transformation and consumption of electricity [nrg_cb_e]",,Low,,,,,,
,PM 10 emissions,g / kWh,  0.01 ,  0.01 ,"Calculated based on Eurostat data, DATASET: Air pollutants by source sector (source: EEA) [env_air_emis] & DATASET: Supply, transformation and consumption of electricity [nrg_cb_e]",,Low,,,,,,
,,,,,,,,,,,,,
,Other,,,,,,,,,,,,
,Spot price electricity,EUR/MWh,  50 ,  50 ,2022 spot price average,,High,,,,,,
,,,,,,,,,,,,,
,Solar PV,,,,,,,,,,,,
,Solar electricity produced by solar PVs,kWh per year/kW,"  1,451 ","  1,451 ",Valencia - 2019,,Low,,Part of renewable sources (row 165),,,,
,Yearly average of solar electricity generated by 1 m2 solar PV,kWh/m2,  200 ,  200 ,Material Economics analysis,,Low,,,,,,
,,,,,,,,,,,,,
,,,,,,,,,,,,,
,Waste,,,,,,,Add source here,Comment,,,,
,Waste generation / collection,,,,,,,,,,,,
,Total collected waste within city boundaries,tonne,"  388,337 ","  388,337 ","  379,597 ",,,,,,,,
,,,,,,,,,,,,,
,Total collected waste within city boundaries,,,,,,,,,,,,
,Paper and cardboard,tonne,"  68,669 ","  68,669 ","  67,124 ",,High,Example comment,,,,,
,Metal,tonne,"  13,965 ","  13,965 ","  13,651 ",,High,,,,,,
,Plastics,tonne,"  56,773 ","  56,773 ","  55,495 ",,High,,,,,,
,Glass,tonne,"  28,835 ","  28,835 ","  28,186 ",,High,,,,,,
,Organic waste,tonne,"  139,462 ","  139,462 ","  136,323 ",,High,,,,,,
,"Other waste (e.g. textiles, rubble, wood etc)",tonne,"  80,633 ","  80,633 ","  78,818 ",,High,,,,,,
,,,,,,,,,,,,,
,,,,,,,,,,,,,
,Share recycling/incineration/landfill,,,,,,,,,,,,
,Paper waste,,,,,,,,,,,,
,Share of paper waste - other (e.g. landfilled),Share,8%,8%,"Eurostat, DATASET: Packaging waste by waste management operations and waste flow [env_waspac]",,High,,,,,,
,Share of paper waste - incinerated (e.g. energy recovery),Share,7%,7%,"Eurostat, DATASET: Packaging waste by waste management operations and waste flow [env_waspac]",,High,,,,,,
,Share of paper waste - recycled,Share,85%,85%,"Eurostat, DATASET: Packaging waste by waste management operations and waste flow [env_waspac]",,High,,,,,,
,Total,Share,100%,100%,,0%,,,Should sum to 100%,,,,
,,,,,,,,,,,,,
,Metal waste,,,,,,,,,,,,
,Share of metal waste - landfilled,Share,20%,20%,"Eurostat, DATASET: Packaging waste by waste management operations and waste flow [env_waspac]",,High,,,,,,
,Share of metal waste - incinerated (e.g. energy recovery),Share,1%,1%,"Eurostat, DATASET: Packaging waste by waste management operations and waste flow [env_waspac]",,High,,,,,,
,Share of metal waste - recycled,Share,79%,79%,"Eurostat, DATASET: Packaging waste by waste management operations and waste flow [env_waspac]",,High,,,,,,
,Total,Share,100%,100%,,0%,,,Should sum to 100%,,,,
,,,,,,,,,, , , , 
,Plastic waste,,,,,,,,,,,,
,Share of plastic waste - landfilled,Share,25%,25%,"Eurostat, DATASET: Packaging waste by waste management operations and waste flow [env_waspac]",,High,,,,,,
,Share of plastic waste - incinerated (e.g. energy recovery),Share,33%,33%,"Eurostat, DATASET: Packaging waste by waste management operations and waste flow [env_waspac]",,High,,,,,,
,Share of plastic waste - recycled,Share,42%,42%,"Eurostat, DATASET: Packaging waste by waste management operations and waste flow [env_waspac]",,High,,,,,,
,Total,Share,100%,100%,,0%,,,Should sum to 100%,,,,
,,,,,,,,,,,,,
,Glass waste,,,,,,,,,,,,
,Share of glass waste - landfilled,Share,26%,26%,"Eurostat, DATASET: Packaging waste by waste management operations and waste flow [env_waspac]",,High,,,,,,
,Share of glass waste - incinerated (e.g. energy recovery),Share,0%,0%,"Eurostat, DATASET: Packaging waste by waste management operations and waste flow [env_waspac]",,High,,,,,,
,Share of glass waste - recycled,Share,74%,74%,"Eurostat, DATASET: Packaging waste by waste management operations and waste flow [env_waspac]",,High,,,,,,
,Total,Share,100%,100%,,0%,,,Should sum to 100%,,,,
,,,,,,,,,,,,,
,Organic waste,,,,,,,,,,,,
,Share of organic waste - landfilled,Share,23%,23%,"Calculated based on Eurostat, DATASET: Municipal waste by waste management operations [env_wasmun] & Gershman, Brickner & Bratton, Inc (2016) - European Technology Overview: Anaerobic Digestion (AD) of the Organic Fraction of the MSW. http://gbbinc.com/wp-content/uploads/2016/05/ArsovaRutgers2016.pdf",,High,,,,,,
,Share of organic waste - incinerated (e.g. energy recovery),Share,23%,23%,"Calculated based on Eurostat, DATASET: Municipal waste by waste management operations [env_wasmun] & Gershman, Brickner & Bratton, Inc (2016) - European Technology Overview: Anaerobic Digestion (AD) of the Organic Fraction of the MSW. http://gbbinc.com/wp-content/uploads/2016/05/ArsovaRutgers2016.pdf",,High,,,,,,
,Share of organic waste - composted,Share,54%,54%,"Calculated based on Eurostat, DATASET: Municipal waste by waste management operations [env_wasmun] & Gershman, Brickner & Bratton, Inc (2016) - European Technology Overview: Anaerobic Digestion (AD) of the Organic Fraction of the MSW. http://gbbinc.com/wp-content/uploads/2016/05/ArsovaRutgers2016.pdf",,High,,,,,,
,Total,Share,100%,100%,,0%,,,Should sum to 100%,,,,
,,,,,,,,,,,,,
,"Other waste (e.g. textiles, rubble, wood)",,,,,,,,,,,,
,"Share of ""other"" waste - landfilled",Share,36%,36%,"Calculated based on Eurostat, DATASET: Municipal waste by waste management operations [env_wasmun] & Gershman, Brickner & Bratton, Inc (2016) - European Technology Overview: Anaerobic Digestion (AD) of the Organic Fraction of the MSW. http://gbbinc.com/wp-content/uploads/2016/05/ArsovaRutgers2016.pdf",,High,,,,,,
,"Share of ""other"" waste - incinerated (e.g. energy recovery)",Share,54%,54%,"Calculated based on Eurostat, DATASET: Municipal waste by waste management operations [env_wasmun] & Gershman, Brickner & Bratton, Inc (2016) - European Technology Overview: Anaerobic Digestion (AD) of the Organic Fraction of the MSW. http://gbbinc.com/wp-content/uploads/2016/05/ArsovaRutgers2016.pdf",,High,,,,,,
,"Share of ""other"" waste - recycled",Share,10%,10%,"Calculated based on Eurostat, DATASET: Municipal waste by waste management operations [env_wasmun] & Gershman, Brickner & Bratton, Inc (2016) - European Technology Overview: Anaerobic Digestion (AD) of the Organic Fraction of the MSW. http://gbbinc.com/wp-content/uploads/2016/05/ArsovaRutgers2016.pdf",,High,,,,,,
,Total,Share,100%,100%,,0%,,,Should sum to 100%,,,,
,,,,,,,,,,,,,
,Emission factors from waste management,,,,,,,,,,,,
,Incineration,,,,,,,,,,,,
,CO2e emissions,kg / tonne waste incinerated,  633 ,  633 ,"Atmospheric emissions Inventory of Madrid City, 2017. Including emissions from auxiliary fuel. Only  fossil CO2",,High,,,,,,
,NOx emissions,kg / tonne waste incinerated,  0.53 ,  0.53 ,"Atmospheric emissions Inventory of Madrid City, 2017. Including emissions from auxiliary fuel",,Low,,,,,,
,PM 2.5 emissions,kg / tonne waste incinerated,  0.00 ,  0.00 ,"Atmospheric emissions Inventory of Madrid City, 2017. Including emissions from auxiliary fuel",,Low,,,,,,
,PM 10 emissions,kg / tonne waste incinerated,  0.00 ,  0.00 ,"Atmospheric emissions Inventory of Madrid City, 2017. Including emissions from auxiliary fuel",,Low,,,,,,
,,,,,,,,,,,,,
,,,,,,,,,,,,,
,Other price data,,,,,,,Add source here,Comment,,,,
,Energy prices,,,,,,,,,,,,
,Retail price of electricity,€/kWh,  0.28 ,  0.28 ,2022 retail price of to align with spot price on line 177,,Moderate,,,,,,
,Retail price of heating,€/MWh,  152.00 ,  152.00 ,2022 retail price average,,Moderate,,,,,,
,,,,,,,,,,,,,
,,,,,,,,,,,,,
,Greenhouse gases (CO2 emissions other greenhouse gases),,,,,,,Add source here,Comment,,,,
,Total greenhouse emissions (GHG),,,,,,,,,,,,
,Total emissions (scope 1 & scope 2; scope 3 only for waste disposed of outside city boundaries),kton CO2e / year,"  1,622 ","  1,622 ","  1,585 ",,,,,,,,
,,,,,,,,,,,,,
,Emissions from road transportation,,,,Valencia 2019 SECAP,,,,,,,,
,Total emissions from road transport,kton CO2e / year,  637 ,  637 ,  623 ,,,,Excludes electricity,,,,
,Passenger cars + motorcycles,kton CO2e / year,  485 ,  485 ,  474 ,,High,,,,,,
,Light duty trucks <3.5 tonne,kton CO2e / year,  57 ,  57 ,  56 ,,High,,,,,,
,Heavy duty trucks >3.5 tonne,kton CO2e / year,  33 ,  33 ,  32 ,,High,,,,,,
,Buses,kton CO2e / year,  49 ,  49 ,  48 ,,High,,,,,,
,Other motorized transport,kton CO2e / year,  13 ,  13 ,  13 ,,High,,,,,,
,,,,,Valencia 2019 SECAP,,,,,,,,
,Emissions from buildings & heating,,  193 ,  193 ,  189 ,,,,Excludes electricity,,,,
,Heating & hot water,kton CO2e / year,  193 ,  193 ,  189 ,,High,,,,,,
,Cooling,kton CO2e / year,  -   ,  -   ,  -   ,,High,,,,,,
,Other building-related emissions,kton CO2e / year,  -   ,  -   ,  -   ,,High,,,,,,
,,,,,,,,,,,,,
,Emissions from electricity,,,,Valencia 2019 SECAP,,,,,,,,
,Total emissions from electricity demand,kton CO2e / year,  474 ,  474 ,  463 ,,,,Total electricity from all sectors,,,,
,Buildings,kton CO2e / year,  474 ,  474 ,  463 ,,High,,,,,,
,Other,kton CO2e / year,  -   ,  -   ,  -   ,,High,,,,,,
,,,,,Valencia 2019 SECAP,,,,,,,,
,Emissions from waste (including waste disposed of outside of city boundaries),,  71 ,  71 ,  70 ,,,,"Garbage only - sewage falls under ""Other"" sector",,,,
,Incineration of waste,kton CO2e / year,  -   ,  -   ,  -   ,,High,,Excludes electricity,,,,
,Organic decay (waste),kton CO2e / year,  14 ,  14 ,  14 ,,High,,,,,,
,Landfill gas,kton CO2e / year,  55 ,  55 ,  54 ,,High,,,,,,
,Other waste management,kton CO2e / year,  2 ,  2 ,  2 ,,High,,,,,,
,,,,,Valencia 2019 SECAP,,,,,,,,
,Emissions from other sectors,,  247 ,  247 ,  241 ,,,,Excludes electricity,,,,
,Industry (IPPU),kton CO2e / year,  64 ,  64 ,  63 ,,High,,,,,,
,Agriculture (AFOLU),kton CO2e / year,  138 ,  138 ,  135 ,,High,,,,,,
,Other sources,kton CO2e / year,  44 ,  44 ,  43 ,,High,,,,,,
,,,,,,,,,,,,,
,PART 2: City assumptions 2030,,,,,,,,,,,,
,Note: These assumptions should represent a  scenario for how far the city can get to in its decarbonisation efforts in a very ambitious scenario and in alignment with city's Climate Action Plan.,,,,,,,,,,,,
,Key assumptions for levers,,,,,,,Add source here,Comment,,,,
,1. Passenger transportation levers,,,,,,,,,,,,
,1.1 Reduced motorised passenger transportation need,,,,,,,,,,,,
,"Transportation need reduction by 2030 from urban planning, digital meetings and other transport-reducing initiatives",%,35%,35%,Valencia forecast assumption - 2030,,High,,,,,,
,,,,,,,,,,,,,
,1.2 Shift to public and non-motorised transport,,,,,,,,,,,,
,Reduced passenger kilometres by car through shift to public and non-motorised transport,,,,,,,,,,,,
,Reduced Pkm cars + motorcycles by 2030,%,30%,30%,Valencia forecast assumption - 2030,,High,,,,,,
,,,,,,,,,,,,,
,Share of car + motorcycle km reduced shifted towards other modes,,,,,,,,,,,,
,Buses,%,10%,10%,Valencia forecast assumption - 2030,,Moderate,,,,,,
,Trains/metro,%,60%,60%,Valencia forecast assumption - 2030,,Moderate,,,,,,
,Walking/cycling,%,30%,30%,Valencia forecast assumption - 2030,,Moderate,,,,,,
,Total,%,100%,100%,,0%,,,Should sum to 100%,,,,
,,,,,,,,,,,,,
,1.3 Car pooling,,,,,,,,,,,,
,Percentage increase in avg. passengers per car + motorcycles (2030) due to improved transport efficiency from better Car pooling and Mobility as a Service,%,25%,25%,Valencia forecast assumption - 2030,,Moderate,,,,,,
,,,,,,,,,,,,,
,1.4.1 Electrification of passenger cars + motorcycles,,,,,,,,,,,,
,What is the maximum share of the passenger car + motorcycle fleet that can be electrified?,%,35%,35%,Valencia forecast assumption - 2040,,High,,,,,,
,At what year can we expect the city to reach the maximum value specified above?,Year,2040,2040,Valencia forecast assumption - 2040,,High,,,,,,
,,,,,,,,,,,,,
,1.4.2 Electrification of buses,,,,,,,,,,,,
,Expected procurement schedule for buses,,,,,,,,,,,,
,2020,% of fleet exchanged ,0%,0%,Valencia forecast assumption,,High,,,,,,
,2021,% of fleet exchanged ,0%,0%,Valencia forecast assumption,,High,,,,,,
,2022,% of fleet exchanged ,3%,3%,Valencia forecast assumption,,High,,,,,,
,2023,% of fleet exchanged ,10%,10%,Valencia forecast assumption,,High,,,,,,
,2024,% of fleet exchanged ,10%,10%,Valencia forecast assumption,,High,,,,,,
,2025,% of fleet exchanged ,10%,10%,Valencia forecast assumption,,High,,,,,,
,2026,% of fleet exchanged ,10%,10%,Valencia forecast assumption,,High,,,,,,
,2027,% of fleet exchanged ,10%,10%,Valencia forecast assumption,,High,,,,,,
,2028,% of fleet exchanged ,15%,15%,Valencia forecast assumption,,High,,,,,,
,2029,% of fleet exchanged ,15%,15%,Valencia forecast assumption,,High,,,,,,
,2030,% of fleet exchanged ,17%,17%,Valencia forecast assumption,,High,,,,,,
,Total,%,100%,100%,,0%,,,,,,,
,,,,,,,,,,,,,
,2. Freight transportation levers,,,,,,,,,,,,
,2.1 Optimisation of logistics,,,,,,,,,,,,
,Utilisation of trucks in decarbonisation scenario,,,,,,,,,,,,
,Light duty trucks,% of max load weight,45%,45%,"Assuming light trucks can reach average urban distribution today. The ""normal"" utilisation rate is 45% for trucks used for urban distribution, and 70% for trucks used for long distance, according to ACEA (2010) Commercial vehicles and CO2",,Moderate,,,,,,
,Heavy duty trucks,% of max load weight,60%,60%,"Assuming heavy duty trucks can reach almost same rate as long-haul today (60% out of 70%). According to the ACEA report, the ""normal"" utilisation rate is 45% for trucks used for urban distribution, and 70% for trucks used for long distance",,Moderate,,,,,,
,,,,,,,,,,,,,
,Reduction of total distance travelled through route optimisation,% of distance,10%,10%,IEA (2018) - The future of trucks Implications for energy & the environment https://ec.europa.eu/clima/sites/clima/files/events/docs/0121/iea_en.pdf,,,,,,,,
,,,,,,,,,,,,,
,2.2 Electrification of trucks,,,,,,,,,,,,
,Light duty trucks <3.5 tonne,,,,,,,,,,,,
,What is the maximum share of the truck fleet that can be electrified?,%,90%,90%,Valencia forecast assumption - 2040,,High,,,,,,
,At what year can we expect the city to reach the maximum value specified above?,Year,2040,2040,Valencia forecast assumption - 2040,,High,,,,,,
,,,,,,,,,,,,,
,Heavy duty trucks >3.5 tonne,,,,,,,,,,,,
,What is the maximum share of the truck fleet that can be electrified?,%,60%,60%,Valencia forecast assumption - 2040,,High,,,,,,
,At what year can we expect the city to reach the maximum value specified above?,Year,2040,2040,Valencia forecast assumption - 2040,,High,,,,,,
,,,,,,,,,,,,,
,3. Buildings & heating,,,,,,,,,,,,
,3.1 Buildings renovations (envelope),,,,,,,,,,,,
,Renovation rate - decarbonisation scenario,% of building stock / year,2.5%,2.5%,"Assumption, based on BPIE (2011) - ""Europe's buildings under the microscope"". http://bpie.eu/wp-content/uploads/2015/10/HR_EU_B_under_microscope_study.pdf",,High,,,,,,
,,,,,,,,,,,,,
,Assumed share of type of renovation in lever,,,,,,,,,,,,
,Minor heating renovations (0-30% improvement),%,50%,50%,Valencia forecast assumption - 2030,,High,,,,,,
,Extensive heating renovations (30-60% improvement),%,50%,50%,Valencia forecast assumption - 2030,,High,,,,,,
,,,100%,100%,,0%,,,Should sum to 100%,,,,
,,,,,,,,,,,,,
,3.2 Energy efficient new buildings,,,,,,,,,,,,
,Improvement in energy efficiency relative to minimum requirement,%,50%,50%,Valencia forecast assumption - 2030,,Moderate,,,,,,
,,,,,,,,,,,,,
,Share of new buildings built with high energy efficiency standards,,,,,,,,,,,,
,Minimum building standard,Share,70%,70%,Valencia forecast assumption - 2030,,Moderate,,,,,,
,Top performing building standard,Share,30%,30%,Valencia forecast assumption - 2030,,Moderate,,,,,,
,,,100%,100%,,0%,,,Should sum to 100%,,,,
,3.3 Efficient lighting & appliances,,,,,,,,,,,,
,Renovation rate - decarbonisation scenario,% of building stock / year,2.5%,2.5%,"Assumption, based on BPIE (2011) - ""Europe's buildings under the microscope"". http://bpie.eu/wp-content/uploads/2015/10/HR_EU_B_under_microscope_study.pdf",,High,,,,,,
,,,,,,,,,,,,,
,Assumed share of type of efficiency programme for lever,,,,,,,,,,,,
,Minor efficiency improvements for lighting and appliances (~15%),%,0%,0%,Valencia forecast assumption - 2030,,Moderate,,,,,,
,Aggressive efficiency improvements for lighting and appliances (~40%),%,100%,100%,Valencia forecast assumption - 2030,,Moderate,,,,,,
,,,100%,100%,,0%,,,Should sum to 100%,,,,
,3.4 Decarbonising heating,,,,,,,,,,,,
,Heating technologies in 2030,,,,,,,,,,,,
,"Share of heating as district heating, 2030",%,5%,5%,Valencia forecast assumption - 2030,,High,,,,,,
,"Share of heating as local heating, 2030",%,95%,95%,Valencia forecast assumption - 2030,,High,,,,,,
,Total,%,100%,100%,,0%,,,Should sum to 100%,,,,
,,,,,,,,,,,,,
,Share of district heating in 2030 as,,,,,,,,,,,,
,"Fossil (oil, coal, gas) + inefficient electric heating (not heat pumps)",%,0%,0%,Valencia forecast assumption - 2030,,High,,,,,,
,Electric heat pumps / geothermal,%,80%,80%,Valencia forecast assumption - 2030,,High,,,,,,
,"Bio (biogas, biomass)",%,20%,20%,Valencia forecast assumption - 2030,,High,,,,,,
,Waste (fossil & non-fossil waste),%,0%,0%,Valencia forecast assumption - 2030,,High,,,,,,
,Total,%,100%,100%,,0%,,,Should sum to 100%,,,,
,,,,,,,,,,,,,
,Share of waste in 2030 used in district heating that is fossil / non-fossil,,,,,,,,,,,,
,Fossil share,%,18%,18%,Valencia forecast assumption - 2030,,Moderate,,,,,,
,Non-fossil share,%,82%,82%,Valencia forecast assumption - 2030,,Moderate,,,,,,
,Total,%,100%,100%,,0%,,,Should sum to 100%,,,,
,,,,,,,,,,,,,
,Share of local heating in 2030 as,,,,,,,,,,,,
,"Fossil (oil, coal, gas) + inefficient electric heating (not heat pumps)",%,25%,25%,Valencia forecast assumption - 2030,,High,,,,,,
,Electric (heat pumps),%,60%,60%,Valencia forecast assumption - 2030,,High,,,,,,
,Biobased,%,15%,15%,Valencia forecast assumption - 2030,,High,,,,,,
,Total,%,100%,100%,,0%,,,Should sum to 100%,,,,
,,,,,,,,,,,,,
,"Share of current fossil production that would need to be re-invested in by 2030, if current production where to continue",,,,,,,,,,,,
,District heating - fossil re-investments need,%,100%,100%,Valencia forecast assumption - 2030,,Moderate,,,,,,
,Local heating - fossil re-investments need,%,50%,50%,"Assumption, based on an assumed lifetime of ~20 years",,Moderate,,,,,,
,,,,,,,,,,,,,
,,,,,,,,,,,,,
,4. Electricity,,,,,,,,,,,,
,Share renewable/fossil electricity production in 2030,,,,,,,,,,,,
,Share of current fossil production replaced by renewables (or nuclear),%,85%,85%,Spanish national forecast assumption,,High,,,,,,
,,,,,,,,,,,,,
,Distribution of type of new renewables,,,,,,,,,,,,
,Local solar PV (e.g. rooftops),%,5%,5%,Spanish national forecast assumption,,Moderate,,,,,,
,Centralised Solar PV/wind farms,%,95%,95%,Spanish national forecast assumption,,Moderate,,,,,,
,Total,%,100%,100%,,0%,,,Should sum to 100%,,,,
,,,,,,,,,,,,,
,,,,,,,,,,,,,
,5. Waste,,,,,,,,,,,,
,5.1. Increased recycling of waste,,,,,,,,,,,,
,"Treatement of paper, 2030",,,,,,,,,,,,
,Landfill ,%,0%,0%,,,High,,,,,,
,Incineration,%,15%,15%,,,High,,,,,,
,Recycling,%,85%,85%,"Assumption that recycling rate stays the same as EU-levels, but landfill decreases from 8% to 0%",,High,,,,,,
,Total,%,100%,100%,,0%,High,,Should sum to 100%,,,,
,,,,,,,,,,,,,
,"Treatment of metals, 2030",,,,,,,,,,,,
,Landfill ,%,10%,10%,Based on EU target for municipal waste: maximum 10% to landfill,,High,,,,,,
,Incineration,%,5%,5%,,,High,,,,,,
,Recycling,%,85%,85%,Assumption made by Material Economics that the recycling rate of metals 2030 can be the same as the rate for paper is today,,High,,,,,,
,Total,%,100%,100%,,0%,,,Should sum to 100%,,,,
,,,,,,,,,,,,,
,"Treatment of plastics, 2030",,,,,,,,,,,,
,Landfill ,%,10%,10%,Based on EU target for municipal waste: maximum 10% to landfill,,High,,,,,,
,Incineration,%,22%,22%,,,High,,,,,,
,Recycling,%,68%,68%,"Based on the ambitious scenario from the Material Economics report ""The Circular Economy - a Powerful Force for Climate Mitigation""",,High,,,,,,
,Total,%,100%,100%,,0%,,,Should sum to 100%,,,,
,,,,,,,,,,,,,
,"Treatment of glass, 2030",,,,,,,,,,,,
,Landfill ,%,10%,10%,Based on EU target for municipal waste: maximum 10% to landfill,,High,,,,,,
,Incineration,%,5%,5%,,,High,,,,,,
,Recycling,%,85%,85%,Assumption made by Material Economics that the recycling rate of glass 2030 can be the same as the rate of paper is today,,High,,,,,,
,Total,%,100%,100%,,0%,,,Should sum to 100%,,,,
,,,,,,,,,,,,,
,"Treatment of organic, 2030",,,,,,,,,,,,
,Landfill ,%,0%,0%,,,High,,,,,,
,Incineration,%,15%,15%,,,High,,,,,,
,Composting,%,85%,85%,Assumption made by Material Economics that the recycling rate of organic waste 2030 can be the same as the rate for paper is today,,High,,,,,,
,Total,%,100%,100%,,0%,,,Should sum to 100%,,,,
,,,,,,,,,,,,,
,,,,,,,,,,,,,
,5. Forestation,,,,,,,,,,,,
,,,,,,,,,,,,,
,Number of planted trees until 2030,,,,,,,,,,,,
,Total amount of trees planted,Number of trees,"  100,000 ","  100,000 ",,,,,,,,,
,Trees planted inside city,Number of trees,"  20,000 ","  20,000 ",Zaragoza forecast assumption - 2030,,Low,,,,,,
,Trees planted outside city,Number of trees,"  80,000 ","  80,000 ",Zaragoza forecast assumption - 2030,,Low,,,,,,
,,,,,,,,,,,,,
,Distribution between trees in grey and green area,,,,,,,,,,,,
,Inside city - grey area,% of trees inside city,33%,33%,Based on scenario 1 from Municipality of Milan - Financing Urban Forestation,,Low,,,,,,
,Inside city - green area,% of trees inside city,67%,67%,Based on scenario 1 from Municipality of Milan - Financing Urban Forestation,,Low,,,,,,
,,,100%,100%,,0%,,,Should sum to 100%,,,,
,Outside city - grey area,% of trees outside city,17%,17%,Based on scenario 5 from Municipality of Milan - Financing Urban Forestation,,Low,,,,,,
,Outside city - green area,% of trees outside city,83%,83%,Based on scenario 5 from Municipality of Milan - Financing Urban Forestation,,Low,,,,,,
,,,100%,100%,,0%,,,Should sum to 100%,,,,
,Population density outside city compared to inside city,,,,,,,,,,,,
,Population density outside city (used to scale benefits from forestation),% of population density inside city,10%,10%,Zaragoza - 2019,,Low,,,,,,
,,,,,,,,,,,,,
,,,,,,,,,,,,,
,"Other (Emissions from other sectors: IPPU, AFOLU etc.)",,,,,,,,"Emissions not included in four main sectors of Transportation, Buildings & Heating, Electricity, and Waste",,,,
,"Reduced CO2e emissions committed by Industry, Agriculture, etc. in Other sector",,,,,,,,,,,,
,Percentage CO2e reduction by 2030 in Other sector,%,81%,80%,,81%,High,,Set at % reduction for 4 main sectors unless adjusted by city,,,,`;
