name: CI
on: push

jobs:
  build:
    uses: kausaltech/github-actions/.github/workflows/build.yaml@main
    with:
      project_id: nzc-data-studio
      project_type: nextjs
    secrets:
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  deploy:
    needs: [build]
    uses: kausaltech/github-actions/.github/workflows/deploy.yaml@main
    secrets:
      gitops_pat: ${{ secrets.GHA_GITOPS_PAT }}
    if: needs.build.outputs.deployment_env
    with:
      docker_image_repo: ${{ needs.build.outputs.image }}
      docker_image_tag: ${{ needs.build.outputs.image_tag }}
      project_id: nzc-data-studio
      build_id: ${{ needs.build.outputs.build_id }}
      deployment_env: ${{ needs.build.outputs.deployment_env }}
